export const defaultServices = [
  "House Cleaning",
  "Laundry",
  "Plumbing Repairs",
  "Electrical Repairs",
  "AC Repair",
  "Appliance Repair",
  "Handyman Services",
  "Gardening",
  "Pest Control",
  "Carpentry",
  "Painting",
  "Moving Help",
  "Furniture Assembly",
  "Deep Cleaning",
  "Office Cleaning",
  "Car Wash",
  "Motorcycle Repair",
  "Mobile Phone Repair",
  "Computer Repair",
  "Graphic Design",
  "Web Development",
  "Social Media Management",
  "Photography",
  "Videography",
  "Tutoring",
  "Delivery Rider",
  "Grocery Shopping",
  "Event Staffing",
  "Security Guard",
  "Childcare",
  "Elder Care",
  "Nursing Assistant",
  "Personal Training",
  "Makeup Artist",
  "Hair Styling",
  "Barber Services",
  "Tailoring",
  "Catering",
  "Baking",
  "Translation",
  "Legal Assistant",
];

export const fallbackCountries = [
  "All countries",
  "Kenya",
  "Nigeria",
  "Ghana",
  "South Africa",
  "Uganda",
  "Rwanda",
  "Tanzania",
  "India",
  "Philippines",
];
